# Generated by Django 5.1.1 on 2024-09-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_Number',
            field=models.CharField(default='09101838779', max_length=11),
            preserve_default=False,
        ),
    ]
